import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased dark min-h-screen overflow-y-auto bg-gradient-to-t to-[#202020] from-[#E8550c20] to-40%`}
			>
				{/* <div className="absolute top-0 z-[-2] h-screen w-screen bg-[#E8550c18] bg-[radial-gradient(#ffffff33_1px,#202020_1px)] bg-[size:20px_20px]" /> */}
				{children}
			</body>
		</html>
	);
}
